/**
 * Generate the rule reference.
 *
 *   npm run rules
 *
 * Writes docs/rules.md from the rule table itself, so the reference cannot
 * drift from the code. Every rule already carries its own description and
 * thresholds; restating them by hand would only create a second thing to keep
 * true.
 */

import { writeFileSync } from 'node:fs';
import { RULES, RULE_DISABLED, STRICTNESS_LEVELS } from './core/rules.js';
import { GENRE_IDS, getGenre } from './genre/index.js';

const levelName = (n: number): string => {
  if (n >= RULE_DISABLED) return 'never';
  return STRICTNESS_LEVELS.find((l) => l.level === n)?.id ?? String(n);
};

const lines: string[] = [];

lines.push('# Rule reference');
lines.push('');
lines.push('<!-- Generated by `npm run rules`. Edit src/core/rules.ts, not this file. -->');
lines.push('');
lines.push(`${RULES.length} rules. **Prefers from** is the level at which breaking the rule starts costing a candidate score; **forbids from** is where it becomes a hard veto. See [smoothness.md](smoothness.md) for how the levels work.`);
lines.push('');

const byCategory = new Map<string, typeof RULES>();
for (const rule of RULES) {
  const arr = byCategory.get(rule.category) ?? [];
  arr.push(rule);
  byCategory.set(rule.category, arr);
}

for (const [category, rules] of byCategory) {
  lines.push(`## ${category[0]!.toUpperCase()}${category.slice(1)}`);
  lines.push('');
  lines.push('| Rule | Prefers from | Forbids from | What it catches |');
  lines.push('|---|---|---|---|');
  for (const r of rules) {
    lines.push(`| \`${r.id}\` | ${levelName(r.minLevel)} | ${levelName(r.vetoLevel)} | ${r.description} |`);
  }
  lines.push('');
}

// --- Genre overrides -------------------------------------------------------
const overridden = GENRE_IDS
  .map((id) => [id, getGenre(id)] as const)
  .filter(([, g]) => g.ruleOverrides && Object.keys(g.ruleOverrides).length > 0);

if (overridden.length) {
  lines.push('## Genre overrides');
  lines.push('');
  lines.push('Genres that disagree with a threshold adjust it rather than forking the table.');
  lines.push('');
  for (const [id, genre] of overridden) {
    lines.push(`### ${genre.label}`);
    lines.push('');
    lines.push('| Rule | Prefers from | Forbids from |');
    lines.push('|---|---|---|');
    for (const [ruleId, o] of Object.entries(genre.ruleOverrides!)) {
      const base = RULES.find((r) => r.id === ruleId);
      if (!base) {
        throw new Error(`Genre "${id}" overrides unknown rule "${ruleId}"`);
      }
      lines.push(`| \`${ruleId}\` | ${levelName(o.minLevel ?? base.minLevel)} | ${levelName(o.vetoLevel ?? base.vetoLevel)} |`);
    }
    lines.push('');
  }
}

const out = lines.join('\n');
writeFileSync(new URL('../docs/rules.md', import.meta.url), out);
console.log(`docs/rules.md — ${RULES.length} rules across ${byCategory.size} categories`);
