/**
 * Generate the rule reference.
 *
 *   npm run rules          — write docs/rules.md
 *   npm run rules:check    — fail if docs/rules.md is not what we would write
 *
 * Writes docs/rules.md from the rule table itself, so the reference cannot
 * drift from the code. Every rule already carries its own description and
 * thresholds; restating them by hand would only create a second thing to keep
 * true.
 *
 * **The generated file is checked in, so "cannot drift" needs enforcing rather
 * than asserting.** `verify` used to run the writing mode, which is the one
 * arrangement that never catches anything: writing always succeeds, so the
 * pipeline passed whatever the state of the doc, and its only signal was a
 * modified file in a tree nobody was looking at. It missed 58 stale lines —
 * five genres added to the registry, none of them appearing in the overrides
 * section — across four commits. Regenerating on demand is a convenience for
 * whoever changed a rule; the pipeline wants the assertion, so `--check`
 * compares and exits 1 without touching the file, alongside every other step
 * in `verify`.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { RULES, RULE_DISABLED, STRICTNESS_LEVELS } from './core/rules.js';
import { GENRE_IDS, getGenre } from './genre/index.js';

const levelName = (n: number): string => {
  if (n >= RULE_DISABLED) return 'never';
  return STRICTNESS_LEVELS.find((l) => l.level === n)?.id ?? String(n);
};

const lines: string[] = [];

lines.push('# Rule reference');
lines.push('');
lines.push('<!-- Generated by `npm run rules`. Edit src/core/rules.ts, not this file. -->');
lines.push('');
lines.push(`${RULES.length} rules. **Prefers from** is the level at which breaking the rule starts costing a candidate score; **forbids from** is where it becomes a hard veto. See [smoothness.md](smoothness.md) for how the levels work.`);
lines.push('');

const byCategory = new Map<string, typeof RULES>();
for (const rule of RULES) {
  const arr = byCategory.get(rule.category) ?? [];
  arr.push(rule);
  byCategory.set(rule.category, arr);
}

for (const [category, rules] of byCategory) {
  lines.push(`## ${category[0]!.toUpperCase()}${category.slice(1)}`);
  lines.push('');
  lines.push('| Rule | Prefers from | Forbids from | What it catches |');
  lines.push('|---|---|---|---|');
  for (const r of rules) {
    lines.push(`| \`${r.id}\` | ${levelName(r.minLevel)} | ${levelName(r.vetoLevel)} | ${r.description} |`);
  }
  lines.push('');
}

// --- Genre overrides -------------------------------------------------------
const overridden = GENRE_IDS
  .map((id) => [id, getGenre(id)] as const)
  .filter(([, g]) => g.ruleOverrides && Object.keys(g.ruleOverrides).length > 0);

if (overridden.length) {
  lines.push('## Genre overrides');
  lines.push('');
  lines.push('Genres that disagree with a threshold adjust it rather than forking the table.');
  lines.push('');
  for (const [id, genre] of overridden) {
    lines.push(`### ${genre.label}`);
    lines.push('');
    lines.push('| Rule | Prefers from | Forbids from |');
    lines.push('|---|---|---|');
    for (const [ruleId, o] of Object.entries(genre.ruleOverrides!)) {
      const base = RULES.find((r) => r.id === ruleId);
      if (!base) {
        throw new Error(`Genre "${id}" overrides unknown rule "${ruleId}"`);
      }
      lines.push(`| \`${ruleId}\` | ${levelName(o.minLevel ?? base.minLevel)} | ${levelName(o.vetoLevel ?? base.vetoLevel)} |`);
    }
    lines.push('');
  }
}

const out = lines.join('\n');
const target = new URL('../docs/rules.md', import.meta.url);
const tally = `${RULES.length} rules across ${byCategory.size} categories`;

if (process.argv.includes('--check')) {
  let current: string | null;
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    current = null;
  }
  if (current !== out) {
    // Report the size of the drift rather than the drift itself. A diff belongs
    // to the tool that can colour it; what the pipeline owes the reader is that
    // something is stale, how stale, and the one command that fixes it.
    // Count the way `wc -l` does — the doc ends in a newline, so the naive
    // split leaves an empty final segment and every number in the message
    // would sit one above whatever the reader measures for themselves.
    const countLines = (s: string) => s.split('\n').length - (s.endsWith('\n') ? 1 : 0);
    const was = current === null ? 0 : countLines(current);
    const now = countLines(out);
    console.log(
      current === null
        ? '\ndocs/rules.md is missing.'
        : `\ndocs/rules.md is stale — ${was} lines checked in, ${now} generated from source.`,
    );
    console.log('Run `npm run rules` and commit the result.\n');
    process.exit(1);
  }
  console.log(`docs/rules.md is up to date — ${tally}`);
} else {
  writeFileSync(target, out);
  console.log(`docs/rules.md — ${tally}`);
}
